### ISSUE TITLE
Could not pass event AsyncPlayerChatEvent

### ISSUE THREAD

**Issue by sebastianbinder** [pro-crafting/wg-fight-plugin#24]
```
[14:34:28 ERROR]: Could not pass event AsyncPlayerChatEvent to WarGear v0.12.0-SNAPSHOT Build:325
org.bukkit.event.EventException
        at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[patched_1.10.2.jar:git-Paper-916.1]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.10.2.jar:git-Paper-916.1]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.10.2.jar:git-Paper-916.1]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.10.2.jar:git-Paper-916.1]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) [patched_1.10.2.jar:git-Paper-916.1]
        at net.minecraft.server.v1_10_R1.PlayerConnection.chat(PlayerConnection.java:1311) [patched_1.10.2.jar:git-Paper-916.1]
        at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1226) [patched_1.10.2.jar:git-Paper-916.1]
        at net.minecraft.server.v1_10_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [patched_1.10.2.jar:git-Paper-916.1]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_101]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_101]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_101]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.NullPointerException
        at de.pro_crafting.wg.WgListener.asyncPlayerChatHandler(WgListener.java:86) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor269.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.10.2.jar:git-Paper-916.1]
        ... 12 more
```

**Comment by Postremus** [comment]
gefixed mit version 0.13
